apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-front-dep
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: classicmeone/udagram-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: tcp
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
