apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-dep
  labels:
    app: udagram-api-feed
    service: feed-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
        service: feed-service
    spec:
      volumes:
        - name: aws-secret
          secret:
            secretName: awssecret
      containers:
      - name: udagram-api-feed
        image: classicmeone/udagram-api-feed
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: aws-secret
            readOnly: true
        ports:
        - containerPort: 80
        resources:
         
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_DB
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_HOST
          - name: DIALECT
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: DIALECT
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_PORT
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: JWT_SECRET
          - name: AWS_MEDIA_BUCKET
            valueFrom:
              configMapKeyRef:
                name: config
                key: AWS_MEDIA_BUCKET
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: URL
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: config
                key: profile
          - name: profile
            valueFrom:
              configMapKeyRef:
                name: config
                key: profile
          - name: region
            valueFrom:
              configMapKeyRef:
                name: config
                key: region
         