apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-dep
  labels:
    app: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: classicmeone/udagram-api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_DB
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_HOST
          - name: DIALECT
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: DIALECT
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: POSTGRES_PORT
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: dbjwtsecret
                key: JWT_SECRET
          - name: AWS_MEDIA_BUCKET
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: AWS_MEDIA_BUCKET
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: aws_secret_access_key
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: region
          - name: AWS_PROFILE
            valueFrom:
              secretKeyRef:
                name: awssecret
                key: profile
          