apiVersion: v1
kind: Service
metadata:
  name: feed-service
  labels:
    run: udagram-api-feed
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: udagram-api-feed
    service: feed-service