apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proxy-dep
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
