apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    run: reverseproxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: reverseproxy
  
