apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-dep
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: classicmeone/reverseproxy
        imagePullPolicy: Always           
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
      restartPolicy: Always
