apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: udagram-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: udagram-frontend